os: linux
dist: xenial
cache: pip
language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install -r dev-requirements.txt

before_script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)

script:
  - flake8 --ignore=F403,F405 MRCpy examples
  - flake8 MRCpy/ tests/
  - python -m unittest discover -s tests

deploy:
  - provider: pages
    skip_cleanup: true
    token: $GITHUB_PAGES_TOKEN
    keep_history: true
    repo: MachineLearningBCAM/MRCpy.github.io
    target_branch: master
    fqdn: MRCpy.github.io
    project_name: MRCpy
    local_dir: docs/
    email: bkartheekreddy@gmail.com
    name: Kartheek Reddy