title: MRCpy
description: Supervised Classification using Minimax Approach
remote_theme: carlosperate/jekyll-theme-rtd

# Theme settings:
site_author: Kartheek Reddy
repo_url: "https://github.com/MachineLearningBCAM/Minimax-Risk-Classifiers"
edit_on_github: true
github_docs_folder: true
sticky_navigation: true
prev_next_buttons_location: bottom
search_enabled: true
hljs_style: github-gist
